name: Build LaTeX document
on:
  push:
    branches:
      - master
jobs:
  build_latex:
    if: "contains(github.event.head_commit.message, 'build')"
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      # - name: Upload PDF file
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: PDF
      #     path: main.pdf
      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::build_$(date +"%Y.%m.%d")"
      - name: Release user firmware
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: main.pdf
